ARG ARG_FROM

FROM $ARG_FROM
MAINTAINER Athanasios Tasoglou <athanasios@tasoglou.net>

## Install cpplint (needed for C++ linting with cpplint extension for VS Code)
RUN sudo pip install cpplint

# Launch terminator
CMD ["terminator"]
